### ISSUE TITLE
数据删除后,比如一个数组删掉一个元素后,会把原来删掉的位置变成null

### ISSUE THREAD

**Issue by mike8625** [yx675258207/wxMiniStore#11]
{
  list: [1]
}

我删掉list里面的第一个,结果数据变成了
{
  list:[null]
}
结果我的页面就显示了一个空的元素,能改一下这个bug吗

**Comment by yx675258207** [comment]
你好，这个问题一直都存在...我自己的版本是解决了，可以加个微信测试下嘛？

**Comment by yx675258207** [comment]
1.2.7中已修复，请更新。如有问题可细聊。

**Comment by mike8625** [comment]
不好意思,这两天家里开始装修了,没开电脑...刚试了一下新的版本,没问题了.十分感谢
nullDiff这个函数我也想自己改来着,但是能力有限没看懂....还是大神给力.
某讯自己团队出的那个写的太复杂了,文档也看不懂,还得改原来代码结构. 您这个状态管理的包很小巧,而且不用改以前的代码,很方便

**Comment by yx675258207** [comment]
感谢.., 初衷也是为了不用改原有代码，所以重写了Page和Component。有问题随时提哦。
