### ISSUE TITLE
页面或组件实例在返回上一个页面后出现空

### ISSUE THREAD

**Issue by qq865738120** [yx675258207/wxMiniStore#2]
![image](https://user-images.githubusercontent.com/26243607/54247169-ddb92f00-4572-11e9-93a1-61e911a8d930.png)
这是正常的实例，显示有三个
![image](https://user-images.githubusercontent.com/26243607/54247210-093c1980-4573-11e9-8b89-ed37250a38df.png)
这是点击返回上一页按钮后

**Comment by yx675258207** [comment]
已修复
