### ISSUE TITLE
在store的methods中如何获取store的状态和方法，如何更改状态？

### ISSUE THREAD

**Issue by z-9527** [yx675258207/wxMiniStore#6]

**Comment by yx675258207** [comment]
如果是按照我的文档将store挂载到App中话，任何地方都通过getApp().store获取到实例store。
store.$state 是状态
store.setState 更新状态
至于store中methods的获取，目前是没有提供直接获取方式，因为methods适用范围所致（这里详见文档，也包含获取方式）。

**Comment by C1996** [comment]
那就是在store methods 里面无法更改全局状态吗

**Comment by yx675258207** [comment]
> 那就是在店方法里面无法更改全局状态吗

可以改变的，直接在内部使用store.setState，任何地方都可以改变，只要你能拿到store实例。

**Comment by C1996** [comment]
状态更新了 但是页面没有更新 T.T

**Comment by C1996** [comment]
感谢
