### ISSUE TITLE
pageLisener 中如果使用onShareAppMessage会使得return值无效

### ISSUE THREAD

**Issue by hxzAugustinus** [yx675258207/wxMiniStore#7]
` /*   store.js  */
 pageLisener: {
     onShareAppMessage(ops) {
      if (ops.from === "menu") {
        console.log("ShareAppMessage  menu")
        return {
          title: "自定义标题1",
          path: "/pages/loading/loading",
          imageUrl: "xxxx"
        }
      }
    }
  }

`
这样设置，真机和开发者工具上  title ，imageUrl   无效; 
另外如果我在pageA页面扩展了onShareAppMessage
`
/*    pageA.js  */
  onShareAppMessage(ops) {
    if (ops.from === "button") {
      console.log("ShareAppMessage  button")
      return {
        title: "自定义标题2",
        imageUrl: 'xxxxxx',
        path: "/pages/pDetail/pDetail?xxxx"
      }
    }
   console.log('share end')
  }

`
当点击右上角的分享 **(ops.from === "menu")**，控制台依然会输出‘share end’,
当点击自定义的分享 **(ops.from === "button")**，控制台不会输出‘share end’,
且2种情况title，imageUrl 都无效

**Comment by hxzAugustinus** [comment]
小程序根据是否声明onShareAppMessage，来确定右上角菜单是否显示“转发”按钮，所以在App.Page重构前，预加载时，所有page里的onShareAppMessage都会读取和执行一遍(以确认‘转发’按钮)，执行时估计已经记住了函数地址，重构后的onShareAppMessage指向另外一个地址，导致根本无效。

**Comment by yx675258207** [comment]
pageLisener这块目前只是用于监听周期事件，源码里我没有给与pageLisener提供返回值，因为当时考虑这可能会带来一些副作用。他的主要职责本来也只是用于onLoad、onUnload 。

但是还是有解决方案的：
```js
new Store({
pageLisener: {
    onLoad(options){
      wx.showShareMenu(); // 这一步很关键，开启所有页面的分享。
      this.onShareAppMessage = function () {
        return {
          title: "自定义标题1",
          path: "/pages/loading/loading",
          imageUrl: "xxxx"
        }
      }
    }
  },
})
```
思路是，全局监听所有页面的onLoad，在某页面加载时，覆盖原页面中的 onShareAppMessage。这里还可以自己加判断，比如页面中已存在分享就不覆盖：
```js
new Store({
  pageLisener: {
    onLoad(options){
      if(!this.onShareAppMessage){ //如果原本页面不存在分享
        wx.showShareMenu(); // 这一步很关键，开启所有页面的分享。
        this.onShareAppMessage = function () { //覆盖原本分享
          return {
            title: "自定义标题1",
            path: "/pages/loading/loading",
            imageUrl: "xxxx"
          }
        }
      }
    }
  },
})
```

**Comment by hxzAugustinus** [comment]
算是个折中方案，只是多写了些重复的代码，多谢！
