### ISSUE TITLE
怎么监听store中属性的变化？

### ISSUE THREAD

**Issue by SayoSama** [yx675258207/wxMiniStore#8]
希望在某个属性有变化的时候执行特定的方法，使用Object.defineProperty似乎不太可行。

**Comment by yx675258207** [comment]
目前store没有监听数据变化的功能，每次更新store的唯一途径是通过setState触发，你可以在setState基础上加以封装，下个版本我会考虑增加类似于原生小程序的observers功能。

**Comment by qianyinghuanmie** [comment]
对的，希望能考虑下，目前可能会在你的基础下，自己先改装的用下。。
